plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

social:
  name: P'tit groupe
  links:
    - https://www.instagram.com/leptitgroupe.musique/
    - https://www.youtube.com/@leptitgroupe2370

title: Le P'tit Groupe

tagline: Le p'tit groupe est un collectif d'amis musiciens Lyonnais jouant de la pop, du jazz et du swing!

description: Site internet du p'tit groupe, un collectif d'amis musiciens bases principalement sur Lyon.

url:

author: Corentin Nelias
